apiVersion: v1
kind: Pod
metadata:
  name: multiple-containers
  labels:
    app: jenkinstomcat
    type: frontend
spec:
  containers:
    - name: jenkins
      image: jenkins/jenkins:lts
    - name: tomcat
      image: anilpu3/kubernetes:latest
