apiVersion: v1
kind: Service
metadata: 
  name: multicontainer-service
spec:
  selector: 
    app: jenkinstomcat
  ports:
    - name: jenkins     
      protocol: TCP
      port: 8081
      targetPort: 8080
    - name: tomcat  
      protocol: TCP
      port: 8082
      targetPort: 9090



