apiVersion: v1
kind: Service
metadata:
  name: multicontainer-nodeport-service
spec:
  type: NodePort
  selector:
    app: jenkinstomcat
  ports:
    - name: jenkins
      protocol: TCP
      nodePort: 30005
      port: 8081
      targetPort: 8080
    - name: tomcat
      protocol: TCP
      nodePort: 30006
      port: 8082
      targetPort: 9999
