apiVersion: v1
kind: Service
metadata:
  name: tomcat-node-service
spec:
  type: NodePort
  selector: 
    app: tomcatapps
  ports:
    - protocol: TCP
      nodePort: 30010
      port: 8080
      targetPort: 8080
